name: Run API Tests in Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-in-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t restassured-tests .

      - name: Run tests in Docker container
        run: docker run --name test-runner restassured-tests

      - name: Copy test reports
        run: docker cp test-runner:/app/target/surefire-reports ./surefire-reports

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: surefire-reports
